language: python

cache: pip

matrix:
    include:
        -   python: 3.6
            env: EXASOL_TAG=6.2.4-d1
        -   python: 3.6
            env: EXASOL_TAG=6.1.8-d1
        -   python: 3.6
            env: EXASOL_TAG=6.0.16-d1
        -   python: 3.7
            env: EXASOL_TAG=6.2.4-d1
            dist: xenial
        -   python: 3.7
            env: EXASOL_TAG=6.1.8-d1
            dist: xenial
        -   python: 3.7
            env: EXASOL_TAG=6.0.16-d1
            dist: xenial
        -   python: 3.8
            env: EXASOL_TAG=6.2.4-d1
            dist: xenial
        -   python: 3.8
            env: EXASOL_TAG=6.1.8-d1
            dist: xenial
        -   python: 3.8
            env: EXASOL_TAG=6.0.16-d1
            dist: xenial

services:
  - docker

warnings_are_errors: false

env:
  global:
    - EXAHOST="127.0.0.1:8563"

before_install:
    - docker run --detach --name exasol --privileged -p 127.0.0.1:8563:8888 exasol/docker-db:$EXASOL_TAG

install:
    - sleep 120
    - docker logs exasol

    - pip install -e .[pandas,encrypt,ujson,rapidjson,examples]

script:
    - python examples/00_prepare.py
    - python examples/11_edge_case.py
